#!/usr/bin/env python3
"""Bundle icons/*.svg into icons.js so they can be inlined into markup.

Why inline rather than <img src="icons/x.svg">: an <img> cannot inherit
currentColor, and the design uses the same glyph in ink, grey, offwhite and
white depending on the surface it sits on. Inlining the markup is the only
way one file serves all four.

Two things this script guards against, both of which the raw Figma export
walked into:

  1. Raster payloads. The plugin exported a couple of "icons" that are
     actually photographs with a base64 image embedded in a <pattern> —
     property-1-default.svg alone is 2MB. Those are skipped: they are
     images, not icons, and belong in an <img> tag.

  2. Duplicate ids. Every export numbers its <defs> ids per-file
     (pattern0_60_3838, clip0_22_1846 …). Inline several icons on one page
     and those ids collide, so gradients and clip paths silently bind to
     the wrong element. Each icon's ids are namespaced with its own name
     before bundling.

Run from the project root:  python3 tools/build-icons.py
"""

import glob
import json
import os
import re

MAX_BYTES = 20_000          # anything larger is not a line icon
OUT = "icons.js"


def namespace_ids(svg: str, slug: str) -> str:
    """Rewrite id="x" / url(#x) / href="#x" so two inlined icons can't clash."""
    ids = set(re.findall(r'\bid="([^"]+)"', svg))
    for i in sorted(ids, key=len, reverse=True):
        safe = f"{slug}-{i}"
        svg = svg.replace(f'id="{i}"', f'id="{safe}"')
        svg = svg.replace(f"url(#{i})", f"url(#{safe})")
        svg = svg.replace(f'href="#{i}"', f'href="#{safe}"')
    return svg


def main() -> None:
    icons, skipped = {}, []

    for path in sorted(glob.glob("icons/*.svg")):
        name = os.path.splitext(os.path.basename(path))[0]
        raw = open(path, encoding="utf-8").read()

        if "base64" in raw or len(raw) > MAX_BYTES:
            skipped.append((name, len(raw)))
            continue

        svg = re.sub(r"\s+", " ", raw).strip()
        # the wrapper's .ico-NN class owns the size; the viewBox is untouched
        svg = re.sub(r'\s(width|height)="[^"]*"', "", svg, count=2)
        svg = namespace_ids(svg, name)
        if "aria-hidden" not in svg:
            svg = svg.replace("<svg ", '<svg aria-hidden="true" focusable="false" ', 1)
        icons[name] = svg

    body = json.dumps(icons, indent=2, ensure_ascii=False)
    js = f'''/*
 * icons.js — the Figma icon set, inlined.
 *
 * GENERATED by tools/build-icons.py — do not edit by hand. Re-export from
 * Figma into icons/ and re-run the script.
 *
 * Every glyph draws with stroke/fill: currentColor, so an icon takes the
 * colour of whatever it sits in. Size comes from the .ico-NN class on the
 * wrapper, never from the SVG itself.
 *
 *   window.icon("search")               -> raw <svg> markup
 *   window.iconEl("search", "ico-20")   -> markup wrapped in a sized <span>
 */
(function () {{
  "use strict";

  var ICONS = {body};

  window.PERCAAL_ICONS = ICONS;

  window.icon = function (name) {{
    var svg = ICONS[name];
    if (!svg && typeof console !== "undefined") {{
      console.warn("[percaal] unknown icon:", name);
    }}
    return svg || "";
  }};

  /* Wrapped form. `size` is an .ico-NN class; `cls` is anything extra. */
  window.iconEl = function (name, size, cls) {{
    return (
      '<span class="ico ' + (size || "ico-20") + (cls ? " " + cls : "") + '">' +
      window.icon(name) +
      "</span>"
    );
  }};
}})();
'''
    open(OUT, "w", encoding="utf-8").write(js)
    print(f"{OUT}: {len(icons)} icons, {os.path.getsize(OUT) / 1024:.1f} KB")
    for n, b in skipped:
        print(f"  skipped (raster/oversize): {n}  {b / 1024:.0f} KB")


if __name__ == "__main__":
    main()
